# Generated by Django 3.1.3 on 2020-11-12 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=45)),
                ('receiver', models.CharField(max_length=45)),
                ('message', models.TextField(max_length=500)),
                ('date_time', models.DateTimeField(default='2020-01-01 12:00')),
                ('status', models.BooleanField(default=0)),
                ('social_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.socialnetwork')),
            ],
        ),
    ]
